@echo off

cd override
oggdec #SAct1.ogg
oggdec #SAct2.ogg
oggdec #SAct3.ogg
oggdec #SAttak1.ogg
oggdec #SBattle.ogg
oggdec #SBored.ogg
oggdec #SCrHit.ogg
oggdec #SCrMiss.ogg
oggdec #SDamage.ogg
oggdec #SDay.ogg
oggdec #SDungeo.ogg
oggdec #SDying.ogg
oggdec #SForest.ogg
oggdec #SFull.ogg
oggdec #SHidden.ogg
oggdec #SHurt.ogg
oggdec #SImmun.ogg
oggdec #SLeader.ogg
oggdec #SMeet1.ogg
oggdec #SNight.ogg
oggdec #SSel1.ogg
oggdec #SSel2.ogg
oggdec #SSel3.ogg
oggdec #SSpell.ogg
oggdec #STired.ogg
oggdec #SRom1.ogg
oggdec #SRom2.ogg
oggdec #SRom3.ogg
oggdec #SRom4.ogg
oggdec #SRom5.ogg
oggdec #SRom6.ogg
oggdec #SRom7.ogg
oggdec #SRom8.ogg
oggdec #SRom9.ogg
oggdec #SRom10.ogg
oggdec #SRom11.ogg
oggdec #SRom12.ogg
oggdec #SRom13.ogg
oggdec #SRom14.ogg
oggdec #SRom15.ogg
oggdec #SRom16.ogg
oggdec #SRom17.ogg
oggdec #SRom18.ogg
oggdec #SRom19.ogg
oggdec #SRom20.ogg
oggdec #SRom21.ogg
oggdec #SRom22.ogg
oggdec #SRom23.ogg
oggdec #SRom24.ogg
oggdec #SRom25.ogg
oggdec #SRom26.ogg
oggdec #SRom27.ogg
oggdec #SRom28.ogg
oggdec #SRom29.ogg
oggdec #SRom31.ogg
oggdec #SRom32.ogg
oggdec #SRom33.ogg
oggdec #SRom34.ogg
oggdec #SRom35.ogg
oggdec #SRom36.ogg
oggdec #SRom37.ogg
oggdec #SRom38.ogg
oggdec #SRom39.ogg
oggdec #SRom40.ogg
oggdec #SRom41.ogg
oggdec #SRom42.ogg
oggdec #SRom43.ogg
oggdec #SRom44.ogg
oggdec #SRom46.ogg
oggdec #SRom47.ogg
oggdec #SRom48.ogg
oggdec #SRom49.ogg
oggdec #SRom50.ogg
oggdec #SRom51.ogg
oggdec #SRom52.ogg
oggdec #SRom53.ogg
oggdec #SRom54.ogg
oggdec #SRom55.ogg
oggdec #SRom56.ogg
oggdec #SRom57.ogg
oggdec #SRom58.ogg
oggdec #SRom59.ogg
oggdec #SRom60.ogg
oggdec #SRom61.ogg
oggdec #SRom62.ogg
oggdec #SRom63.ogg
oggdec #SRom64.ogg
oggdec #SRom65.ogg
oggdec #SRom66.ogg
oggdec #SRom67.ogg
oggdec #SRom68.ogg
oggdec #SRom69.ogg
oggdec #SRom70.ogg
oggdec #SRom71.ogg
oggdec #SRom72.ogg
oggdec #SRom73.ogg
oggdec #SRom74.ogg
oggdec #SRom75.ogg
oggdec #SRom76.ogg
oggdec #SRom77.ogg
oggdec #SRom78.ogg
oggdec #SRom79.ogg
oggdec #SRom80.ogg
oggdec #SRom81.ogg
oggdec #SRom82.ogg
oggdec #SRom83.ogg
oggdec #SRom84.ogg
oggdec #SRom85.ogg
oggdec #SRom86.ogg
oggdec #SRom87.ogg
oggdec #SRom88.ogg
oggdec #SRom89.ogg
oggdec #SRom90.ogg
oggdec #SRom91.ogg
oggdec #SRom92.ogg
oggdec #SRom93.ogg
oggdec #SRom94.ogg
oggdec #SRom95.ogg
oggdec #SRom96.ogg
oggdec #SRom97.ogg
oggdec #SRom98.ogg
oggdec #SRom99.ogg
oggdec #SRom100.ogg
oggdec #SRom101.ogg
oggdec #SRom102.ogg
oggdec #SRom103.ogg
oggdec #SRom104.ogg
oggdec #SRom105.ogg
oggdec #SRom106.ogg
oggdec #SRom107.ogg
oggdec #SRom108.ogg
oggdec #SRom109.ogg
oggdec #SRom110.ogg
oggdec #SRom111.ogg
oggdec #SRom112.ogg
oggdec #SRom113.ogg
oggdec #SRom114.ogg
oggdec #SRom115.ogg
oggdec #SRom116.ogg
oggdec #SFli1.ogg
oggdec #SFli2.ogg
oggdec #SFli3.ogg
oggdec #SFli4.ogg
oggdec #SFli5.ogg
oggdec #SFli6.ogg
oggdec #SFli7.ogg
oggdec #SFli8.ogg
oggdec #SFli9.ogg
oggdec #SFli10.ogg
oggdec #SFli11.ogg
oggdec #SFli12.ogg
oggdec #SFli13.ogg
oggdec #SFli14.ogg
oggdec #SFli15.ogg
oggdec #SFli16.ogg
oggdec #SFli17.ogg
oggdec #SFli18.ogg
oggdec #SFli19.ogg
oggdec #SFli20.ogg
oggdec #SFli21.ogg
oggdec #SFli22.ogg
oggdec #SFli23.ogg
oggdec #SFli24.ogg
oggdec #SFli25.ogg
oggdec #SFli27.ogg
oggdec #SFli28.ogg
oggdec #SFli29.ogg
oggdec #SFli30.ogg
oggdec #SFli31.ogg
oggdec #SFli32.ogg
oggdec #SFli33.ogg
oggdec #SFli34.ogg
oggdec #SFli35.ogg
oggdec #SFli36.ogg
oggdec #SFli37.ogg
oggdec #SFli38.ogg
oggdec #SFli39.ogg
oggdec #SFli40.ogg
oggdec #SFli41.ogg
oggdec #SFli42.ogg
oggdec #SFli43.ogg
oggdec #SFli44.ogg
oggdec #SFli45.ogg
oggdec #SFli46.ogg
oggdec #SFli47.ogg
oggdec #SFli48.ogg
oggdec #SFli49.ogg
oggdec #SFli50.ogg
oggdec #SFli51.ogg
oggdec #SFli52.ogg
oggdec #SFli53.ogg
oggdec #SFli54.ogg
oggdec #SFli55.ogg
oggdec #SFli56.ogg
oggdec #SFli57.ogg

del #S*.ogg
del oggdec.exe
