IF
  True()
THEN
  RESPONSE #100
    CutSceneId("#Severian")
    SetGlobal("#SDecisifImnesvale","AR1100",8)
    DisplayStringHead(Myself,@555)
    Wait(5)
    MoveToPoint([1761.3550])
    MoveViewPoint([1722.3546],VERY_FAST)
    ActionOverride(Player1,MoveToPoint([1722.3546]))
    Wait(1)
    Face(4)
    ActionOverride(Player1,Face(12))
    Wait(1)
    ActionOverride("#Severian",Dialog(Player1))
    EndCutSceneMode()
END
