IF
 Global("#SMalloQuete","GLOBAL",3)
THEN
  RESPONSE #100
   CutSceneId("#Severian")
   SetGlobal("#SMalloQuete","GLOBAL",4)
   Wait(1)
   MoveToPoint([571.1008])
   Face(10)
   ActionOverride("#SMallory",DestroySelf())
   ActionOverride("#SMoust",DestroySelf())
   ActionOverride(Player1,CreateItem("#SMoust",0,0,0))
   ActionOverride("#Severian",CreateItem("#SMallo",0,0,0))
   AddJournalEntry(@4000,QUEST)
   SetDialog("#SeverJ")
   EndCutSceneMode()
END